[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower
monitor_speed = 115200
build_src_filter = +<main.cpp> +<Encoder.cpp> +<PIDController.cpp> +<ServoInput.cpp>
lib_deps = khoih-prog/RP2040_PWM@^1.7.0

[env:bringup]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower
monitor_speed = 115200
build_src_filter = +<bringup.cpp> +<Encoder.cpp>
